name: MyTop5
channels:
  - conda-forge
  - defaults
dependencies:
  #Python!
  - python=3.10

  #Core data
  - pandas=2.2.2
  - numpy=1.26.4
  - scipy=1.13.1

  #ML & Recommendations
  - scikit-learn=1.5.1
  - scikit-surprise=1.1.4

  #Testing
  - pytest=8.3.2

  #Jupyter
  - jupyterlab=4.2.5
  - ipykernel=6.29.5

  #Visualizations
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - plotly=5.24.1

  #App & API
  - streamlit=1.38.0
  - requests=2.32.3



  #pip-only packages
  - pip
  - pip:
    - streamlit-searchbox==0.1.20
    #model cloud storage
    - huggingface_hub==0.24.6